name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*'
    branches:
      - test-release

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Build with cross
        run: cross build --release --target ${{ matrix.target }}
      - name: Rename binary for upload
        run: |
          mv target/${{ matrix.target }}/release/althea-l1-relayer althea-l1-relayer-${{ matrix.target }}
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: althea-l1-relayer-${{ matrix.target }}

  build-windows:
    name: Build Windows Binaries
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build for Windows x64
        run: cargo build --release --target x86_64-pc-windows-msvc
      - name: Rename binary for upload
        run: |
          mv target/x86_64-pc-windows-msvc/release/althea-l1-relayer.exe althea-l1-relayer-x86_64-pc-windows-msvc.exe
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: althea-l1-relayer-x86_64-pc-windows-msvc.exe

  build-macos:
    name: Build macOS Binaries
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Add target
        run: rustup target add ${{ matrix.target }}
      - name: Build for macOS
        run: cargo build --release --target ${{ matrix.target }}
      - name: Rename binary for upload
        run: |
          mv target/${{ matrix.target }}/release/althea-l1-relayer althea-l1-relayer-${{ matrix.target }}
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: althea-l1-relayer-${{ matrix.target }}
