name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --all --verbose

  unit-tests:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: Swatinem/rust-cache@v2
    - name: Unit Tests
      run: cargo test --all --verbose 

  clippy:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v2
    - name: Clippy
      run: rustup component add clippy && cargo clippy --all --all-targets --all-features -- -D warnings

  rustfmt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Rustfmt
      run: rustup component add rustfmt && cargo fmt --all -- --check

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Run cargo audit
        run: cargo audit --deny warnings
